name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Make artifacts
      run: make
    - name: Upload pdfs
      uses: actions/upload-artifact@v2
      with:
        name: pdf
        path: pdf/*.pdf
    - name: Upload svgs
      uses: actions/upload-artifact@v2
      with:
        name: svg
        path: svg/*.svg
